name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - fix-dockerfile-and-compose


permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv==0.8.15

      - name: Install ruff
        run: pip install ruff==0.13.0

      - name: Run ruff (lint and format check)
        run: |
          ruff --version
          ruff check .
          ruff format --check .
      
      - name: Run tests (pytest)
        run: |
          pip install pytest==7.2.2
          uv run -m pytest --cov-report xml:coverage-reports/coverage-report.xml --cov=app ./tests/app --junitxml=python-test-report.xml
      
      - name: Get Cover 
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage-reports/coverage-report.xml
            token: ${{ secrets.GITHUB_TOKEN }}   

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lct:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lct:${{ github.sha }}
